#=========================================
#=== Dark Sky hyper-local weather service
#=========================================
# @link https://www.home-assistant.io/integrations/weather.darksky/
#
# - platform: darksky
#  api_key: !secret api_key_darksky
#  mode: daily

#==================================
#=== OpenWeatherMap weather service
#==================================
# @link https://www.home-assistant.io/integrations/openweathermap/
#
- platform: openweathermap
  api_key: !secret api_key_openweathermap
  mode: freedaily