- id: '1718808545650'
  alias: Evening Lamp On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:10:00
  condition: []
  action:
  - type: turn_on
    device_id: 68e699c0fcaaf717287eba44c154522d
    entity_id: d38eff77e9d04884b37fb00347a3e402
    domain: switch
  mode: single
- id: '1718808682084'
  alias: Evening Lamp Off
  description: ''
  trigger:
  - platform: time
    at: '21:36:00'
  condition: []
  action:
  - type: turn_off
    device_id: 68e699c0fcaaf717287eba44c154522d
    entity_id: d38eff77e9d04884b37fb00347a3e402
    domain: switch
  mode: single
- id: '1719590176846'
  alias: Morning Lamp Off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:05:00
  condition: []
  action:
  - type: turn_off
    device_id: 68e699c0fcaaf717287eba44c154522d
    entity_id: d38eff77e9d04884b37fb00347a3e402
    domain: switch
  mode: single
