#================
#=== Automations
#================
# @link https://home-assistant.io/components/automation/
#
automation: !include_dir_merge_list automations/

#============
#=== Cameras
#============
# @link https://home-assistant.io/components/camera/
#
camera: !include_dir_merge_list cameras/

#=======================================
#=== Enable default set of integrations
#=======================================
# @link https://home-assistant.io/components/default_config/
#
default_config:

#========================================
#=== Discover some devices automatically
#========================================
# @link https://home-assistant.io/components/discovery/
#
#discovery:
#  ignore:
#    - igd

#===========================
#=== Enable the official UI
#===========================
# @link https://home-assistant.io/components/frontend/
#
frontend:
  themes: !include_dir_merge_named themes

#=================================================
#=== Combine entities into groups and organize UI
#=================================================
# @link https://home-assistant.io/components/group/
#
group: !include_dir_merge_named groups/

#========================================================
#=== Enable support for tracking state changes over time
#========================================================
# @link https://home-assistant.io/components/history/
#
history: !include misc/history.yaml

#===========================================
#=== Setup basic Home Assistant information
#===========================================
# @link https://www.home-assistant.io/docs/configuration/basic/
#
homeassistant:
  allowlist_external_dirs:
    - !secret allowlist_external_dirs
  customize: !include customize.yaml
  elevation: !secret home_elevation
  external_url: !secret external_url
  latitude: !secret home_latitude
  longitude: !secret home_longitude

#==========================
#=== Enable the web server
#==========================
# @link https://home-assistant.io/components/http/
#
http:
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

#===========================================
#=== InfluxDB to record/graph state changes
#===========================================
# @link https://home-assistant.io/components/influxdb
#
influxdb: !include misc/influxdb.yaml

#======================================
#=== Manually configured Media players
#======================================
# @link https://home-assistant.io/components/media_player/
#
#media_player: !include misc/media_players.yaml

#============
#=== Logbook
#============
logbook: !include misc/logbook.yaml

#======================
#=== Database recorder
#======================
# Limit the number of tracked entities and length of history.
#
# @link https://home-assistant.io/components/recorder/
#
recorder: !include misc/recorder.yaml

#============
#=== Scripts
#============
# @link https://home-assistant.io/components/script/
#
script: !include_dir_named scripts/

#============
#=== Sensors
#============
# @link https://home-assistant.io/components/sensor/
#
sensor: !include_dir_merge_list sensors/

#=============
#=== Switches
#=============
# @link https://home-assistant.io/components/switch/
#
switch: !include_dir_merge_list switches/

#============
#=== Weather
#============
# @link https://home-assistant.io/components/weather/
#
weather: !include misc/weather.yaml

#==========
#=== Zones
#==========
# @link https://home-assistant.io/components/zone/
#
zone: !include misc/zones.yaml

scene: !include scenes.yaml
