homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # Customization file
  customize: !include customize.yaml
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Enables configuration UI
config:
# Discover some devices automatically
discovery:
# View all events in a logbook
logbook:
# Component responsible for storing details in a database
recorder:
  purge_keep_days: 5
# Track the sun
sun:
# Enables the system health component in the developer tools under "i"
system_health:
updater:
  include_used_components: true
# Additional panel links
panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: !secret grafana_url
# Weather
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily
# Cameras
camera:
  - platform: mjpeg
    name: iCam
    mjpeg_url: !secret cam_url
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
# Enables the frontend
frontend:
  themes: !include themes.yaml
history: !include history.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml 
