homeassistant:
  customize: !include customize.yaml
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Enables a default set of integrations
default_config:
# Discover some devices automatically
discovery:
# Define devices manually
media_player:
  - platform: samsungtv
    host: "192.168.0.224"
    name: "Samsung TV"
    mac: "5c:a3:9d:18:fd:c8"
# Component responsible for storing details in a database
recorder:
  purge_keep_days: 5
# Weather
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily
# Cameras
camera:
  - platform: mjpeg
    name: iCam
    mjpeg_url: !secret cam_url
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
history: !include history.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml 
