background: var(--background-image)
custom_header:
  background: rgba(155, 155, 155, 0.25)
  button_text:
    options: ':'
  compact_mode: true
  swipe_animate: fade
  swipe_prevent_default: true
title: ''
views:
  - badges:
      - sensor.dht_sensor_humidity
      - sensor.dht_sensor_temperature
      - sun.sun
      - media_player.un55f8000
      - binary_sensor.updater
    cards:
      - type: custom:weather-card
        entity: weather.pirateweather
        number_of_forecasts: '5'
        current: true
        forecast: true
        hourly_forecast: false
      - entities:
          - entity: sensor.to_erie
          - entity: sensor.to_parachute
          - entity: sensor.to_south_denver
        type: custom:travel-time-card
    icon: mdi:home-circle
    path: default_view
    title: Main
  - badges: []
    cards:
      - align_header: left
        align_state: left
        animate: true
        entities:
          - color: '#d800f5'
            entity: sensor.pirateweather_temperature
            name: Outdoor
            show_state: true
            state_adaptive_color: true
          - color: '#dbe300'
            entity: sensor.dht_sensor_temperature
            name: Indoor
            show_state: true
            state_adaptive_color: true
          - color: '#ff0000'
            entity: sensor.freezing_point
            show_fill: false
            state_adaptive_color: true
        hours_to_show: 72
        labels: true
        line_width: 1
        name: Temperature (72h)
        points_per_hour: 4
        show: null
        type: custom:mini-graph-card
      - align_header: left
        align_state: left
        animate: true
        entities:
          - color: '#00d62b'
            entity: sensor.pirateweather_humidity
            name: Outdoor
            show_state: true
            state_adaptive_color: true
          - color: '#1259f3'
            entity: sensor.dht_sensor_humidity
            name: Indoor
            show_state: true
            state_adaptive_color: true
        hours_to_show: 72
        labels: true
        line_width: 1
        name: Humidity (72h)
        points_per_hour: 4
        show: null
        type: custom:mini-graph-card
      - aspect_ratio: 0%
        camera_image: camera.radar_wu_colorado
        entities: []
        image: https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
        type: picture-glance
    icon: mdi:weather-cloudy
    title: Weather
  - badges: []
    cards:
      - card:
          show_header_toggle: false
          title: TVs
        entities:
          - media_player.samsung_un55f8000
          - media_player.family_room_tv
        state_filter:
          - 'on'
          - 'off'
        type: entity-filter
      - entity: media_player.chromecast_ultra
        type: media-control
      - entities:
          - entity: switch.pops_desktop
          - entity: switch.stephen_s_desktop
        show_header_toggle: false
        title: Computer Switches
        type: entities
    icon: mdi:monitor-cellphone-star
    title: Devices
  - badges: []
    cards:
      - entities:
          - entity: sensor.to_erie
          - entity: sensor.to_parachute
          - entity: sensor.to_south_denver
        type: custom:travel-time-card
      - align_header: left
        align_state: left
        animate: true
        entities:
          - entity: sensor.to_erie
            index: 2
            name: Erie
            show_state: true
            state_adaptive_color: true
          - entity: sensor.to_south_denver
            index: 1
            name: South Denver
            show_state: true
            state_adaptive_color: true
          - entity: sensor.to_parachute
            index: 3
            name: Parachute
            show_state: true
            state_adaptive_color: true
        hours_to_show: 72
        labels: true
        line_width: 2
        name: Historical Travel Time (72h)
        points_per_hour: 4
        show: null
        type: custom:mini-graph-card
    icon: mdi:car
    path: commuting
    title: Commuting
  - title: SpaceX
    path: spacex
    icon: mdi:rocket
    badges: []
    cards:
      - type: entity
        entity: sensor.starman_distance
      - type: gauge
        entity: sensor.starman_speed
        min: 0
        max: 100000
      - type: entities
        entities:
          - sensor.latest_launch_day
          - sensor.latest_launch_mission
          - sensor.latest_launch_payload
          - sensor.latest_launch_rocket
          - sensor.latest_launch_site
          - sensor.latest_launch_time
          - binary_sensor.launch_within_20_minutes
          - binary_sensor.launch_within_24_hours
          - sensor.next_confirmed_launch_day
          - sensor.next_confirmed_launch_time
          - binary_sensor.next_launch_confirmed
          - sensor.next_launch_day
          - sensor.next_launch_mission
          - sensor.next_launch_payload
          - sensor.next_launch_rocket
          - sensor.next_launch_site
          - sensor.next_launch_time
        title: SpaceX
