title: Home
views:
  - path: default_view
    title: Home
    cards:
      - show_name: true
        show_icon: true
        show_state: true
        type: glance
        entities:
          - entity: sensor.broadlink_rm4_mini_temperature
          - entity: sensor.broadlink_rm4_mini_humidity
          - entity: media_player.un55f8000
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.forecast_home
        forecast_type: daily
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.sonoff_s31_lite_zb_switch
        name: Lamp
      - type: entities
        entities:
          - entity: sensor.arris_sbg6700_ac_download_speed
            name: Download speed
          - entity: sensor.arris_sbg6700_ac_upload_speed
            name: Upload speed
        title: ARRIS SBG6700-AC
      - graph: line
        type: sensor
        entity: sensor.arris_sbg6700_ac_download_speed
        detail: 2
        hours_to_show: 24
      - type: history-graph
        entities:
          - entity: media_player.un55f8000
      - type: entities
        entities:
          - entity: button.wake_on_lan_e0_d5_5e_6d_65_d9
          - entity: button.wake_on_lan_70_8b_cd_54_5a_6b
