#=============================
#=== Temperature and Humidity
#=============================
# @link https://www.home-assistant.io/integrations/dht/
#
- platform: dht
  sensor: DHT22
  pin: 2
  monitored_conditions:
    - temperature
    - humidity


#=====================
#=== Template sensors
#=====================
# @link https://www.home-assistant.io/integrations/template/
#
- platform: template
  sensors:

  #----- Freezing Point
    freezing_point:
      value_template: 32
      friendly_name: Freezing Point
      unit_of_measurement: '°F'
