#============================
#=== Travel routes and times
#============================
# @link https://www.home-assistant.io/integrations/waze_travel_time/
#

#=========================
#=== To Conifer
#=========================
- platform: waze_travel_time
  name: "To Conifer"
  origin: Home
  destination: conifer
  region: "US"
  avoid_toll_roads: true

#============
#=== To Erie
#============
- platform: waze_travel_time
  name: "To Erie"
  origin: Home
  destination: erie
  region: "US"
  avoid_toll_roads: true

#=================
#=== To Parachute
#=================
- platform: waze_travel_time
  name: "To Parachute"
  origin: Home
  destination: parachute
  region: "US"
  avoid_toll_roads: true

#====================
#=== To South Denver
#====================
- platform: waze_travel_time
  name: "To South Denver"
  origin: Home
  destination: south_denver
  region: "US"
  avoid_toll_roads: true
