#============================
#=== Travel routes and times
#============================
# @link https://www.home-assistant.io/integrations/waze_travel_time/
#
- platform: waze_travel_time
  name: "To Hancocks"
  origin: Home
  destination: Hancocks
  region: 'US'
  avoid_toll_roads: false


- platform: waze_travel_time
  name: "To Micahs"
  origin: Home
  destination: Micahs
  region: 'US' 
  avoid_toll_roads: true


- platform: waze_travel_time
  name: "To Austins"
  origin: Home
  destination: Austins
  region: 'US' 
  avoid_toll_roads: true
