#=====================
#=== Weather forecast
#=====================
# @link https://www.home-assistant.io/integrations/darksky/
#
- platform: darksky
  api_key: !secret api_key_darksky
  monitored_conditions:
    - temperature 
    - humidity
